[general]
base_dir = .
targets = build
prefer_beta = False
prefer_newer = True

[plugin:bluemap]
name = Bluemap
enabled = True
targets = build,map
url = https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v5.15/bluemap-5.15-spigot.jar
cleanup_globs = bluemap*.jar

[plugin:chatfilter]
name = ChatFilter
enabled = True
url = None
cleanup_globs = chatFilter*.jar

[plugin:essentialsx]
name = EssentialsX
enabled = False
url = https://cdn.modrinth.com/data/hXiIvTyT/versions/Oa9ZDzZq/EssentialsX-2.21.5.jar
cleanup_globs = Essentials*.jar
prefer_newer = False

[plugin:floodgate]
name = Floodgate
enabled = True
targets = build,map
url = https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
cleanup_globs = floodgate-*.jar
prefer_newer = False

[plugin:geyser]
name = Geyser
enabled = True
targets = build,map
url = https://download.geysermc.org/v2/projects/geyserpreview/versions/latest/builds/latest/downloads/spigot
# url = https://download.geysermc.org/v2/projects/geyserpreview/versions/pr.6452/builds/latest/downloads/spigot
cleanup_globs = Geyser*.jar
prefer_newer = False

[plugin:geyserupdater]
name = GeyserUpdater
enabled = False
targets = build,map
url = https://cdn.modrinth.com/data/GOBGotbW/versions/B5DkkA9m/geyserupdater-spigot.jar
cleanup_globs = geyserupdater*.jar
prefer_newer = True

[plugin:joincommands]
name = JoinCommands
enabled = True
url = https://hangarcdn.papermc.io/plugins/SirBlobman/JoinCommands/versions/3.1.0.120/PAPER/JoinCommands-3.1.0.120.jar
cleanup_globs = JoinCommands*.jar

[plugin:luckperms]
name = LuckPerms
enabled = True
url = https://cdn.modrinth.com/data/Vebnzrzj/versions/OrIs0S6b/LuckPerms-Bukkit-5.5.17.jar
cleanup_globs = LuckPerms*.jar

[plugin:multiverse-core]
name = Multiverse-Core
enabled = True
url = https://cdn.modrinth.com/data/3wmN97b8/versions/SDn3Tk8U/multiverse-core-5.5.0.jar
cleanup_globs = Multiverse-Core*.jar, MultiverseCore*.jar, multiverse-core*.jar

[plugin:plotsquared]
name = PlotSquared-Bukkit
enabled = False
url = None
cleanup_globs = plotsquared-bukkit*.jar
prefer_newer = False

[plugin:protocollib]
name = ProtocolLib
enabled = True
url = None
cleanup_globs = ProtocolLib*.jar

[plugin:vault]
name = Vault
enabled = True
url = https://cdn.modrinth.com/data/87UZeaFi/versions/SWR3fOH6/VaultPlugin-2.0.1.jar
cleanup_globs = Vault*.jar

[plugin:worldborder]
name = WorldBorder
enabled = True
url = https://github.com/PryPurity/WorldBorder/releases/download/v2.1.5/WorldBorder.jar
cleanup_globs = WorldBorder*.jar, worldborder*.jar

[plugin:worldedit]
name = WorldEdit
enabled = True
url = https://cdn.modrinth.com/data/1u6JkXh5/versions/CkT32vix/worldedit-bukkit-7.4.0.jar
cleanup_globs = worldedit*.jar, worldedit-bukkit*.jar

[plugin:viaversion]
name = ViaVersion
enabled = True
cleanup_globs = ViaVersion*.jar

