#!/usr/bin/env bash
set -euo pipefail

MC_DIR="/mc"
CFG="${MC_DIR}/server.properties"
JAR="${MC_DIR}/spigot.jar"
PLUGINS_DIR="${MC_DIR}/plugins"
HOSTNAME="${HOSTNAME:-Minecraft Server}"

# ------------------------------------------------------------
# Optional background helpers (same behavior as your old script)
# ------------------------------------------------------------
mkdir -p "${MC_DIR}"
if command -v python3 >/dev/null 2>&1; then
  if [ -f "${MC_DIR}/advertise.py" ]; then
    python3 "${MC_DIR}/advertise.py" "${HOSTNAME:-Build Server}" &
  fi
  SERVER_IP_DISC="$(ip route get 1.1.1.1 2>/dev/null | awk '/src/ {for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')"
  if [ -n "${SERVER_IP_DISC:-}" ] && [ -f "${MC_DIR}/stats.py" ]; then
    echo "$SERVER_IP_DISC" | python3 "${MC_DIR}/stats.py" &
  fi
fi

# ------------------------------------------------------------
# Defaults for ALL your old env vars (plus RCON_PORT)
# ------------------------------------------------------------
MAX_TICK_TIME="${MAX_TICK_TIME:-60000}"
GAMEMODE="${GAMEMODE:-creative}"
GENERATOR_SETTINGS="${GENERATOR_SETTINGS:-}"
FORCE_GAMEMODE="${FORCE_GAMEMODE:-false}"
ALLOW_NETHER="${ALLOW_NETHER:-true}"
ENFORCE_WHITELIST="${ENFORCE_WHITELIST:-false}"
ENABLE_QUERY="${ENABLE_QUERY:-true}"
PLAYER_IDLE_TIMEOUT="${PLAYER_IDLE_TIMEOUT:-0}"
DIFFICULTY="${DIFFICULTY:-1}"
SPAWN_MONSTERS="${SPAWN_MONSTERS:-false}"
OP_PERMISSION_LEVEL="${OP_PERMISSION_LEVEL:-4}"
PVP="${PVP:-true}"
SNOOPER_ENABLED="${SNOOPER_ENABLED:-true}"
LEVEL_TYPE="${LEVEL_TYPE:-DEFAULT}"
HARDCORE="${HARDCORE:-false}"
ENABLE_COMMAND_BLOCK="${ENABLE_COMMAND_BLOCK:-false}"
MAX_PLAYERS="${MAX_PLAYERS:-100}"
NETWORK_COMPRESSION_THRESHOLD="${NETWORK_COMPRESSION_THRESHOLD:-256}"
RESOURCE_PACK_SHA1="${RESOURCE_PACK_SHA1:-}"
MAX_WORLD_SIZE="${MAX_WORLD_SIZE:-29999984}"
SERVER_PORT="${SERVER_PORT:-25565}"
SERVER_IP="${SERVER_IP:-}"
SPAWN_NPCS="${SPAWN_NPCS:-false}"
ALLOW_FLIGHT="${ALLOW_FLIGHT:-false}"
LEVEL_NAME="${LEVEL_NAME:-world}"
VIEW_DISTANCE="${VIEW_DISTANCE:-10}"
RESOURCE_PACK="${RESOURCE_PACK:-}"
SPAWN_ANIMALS="${SPAWN_ANIMALS:-true}"
WHITE_LIST="${WHITE_LIST:-false}"
GENERATE_STRUCTURES="${GENERATE_STRUCTURES:-true}"
ONLINE_MODE="${ONLINE_MODE:-true}"
MAX_BUILD_HEIGHT="${MAX_BUILD_HEIGHT:-256}"
LEVEL_SEED="${LEVEL_SEED:-}"
PREVENT_PROXY_CONNECTIONS="${PREVENT_PROXY_CONNECTIONS:-false}"
USE_NATIVE_TRANSPORT="${USE_NATIVE_TRANSPORT:-true}"
ENABLE_RCON="${ENABLE_RCON:-true}"
RCON_PASSWORD="${RCON_PASSWORD:-DEFAULT_ADMIN_PASSWORD}"
RCON_PORT="${RCON_PORT:-25575}"
MOTD="${MOTD:-Welcome to the Minecraft Server}"
SPAWN_PROTECTION="${SPAWN_PROTECTION:-4}"
MAP_URL="${MAP_URL:-}"
FRESH_WORLD="${FRESH_WORLD:-false}"

# Memory/JVM handling
MEMORY="${MEMORY:-6G}"
XMS="${XMS:-$MEMORY}"
XMX="${XMX:-$MEMORY}"
JVM_OPTS="${JVM_OPTS:--XX:+UseG1GC -Dfile.encoding=UTF-8}"

# EULA (required)
EULA="${EULA:-TRUE}"

# ------------------------------------------------------------
# EULA enforcement
# ------------------------------------------------------------
if [ "${EULA^^}" != "TRUE" ]; then
  echo "You must accept the Minecraft EULA. Start with -e EULA=TRUE" >&2
  exit 1
fi
echo "eula=true" > "${MC_DIR}/eula.txt"

# ------------------------------------------------------------
# Safe property setter (creates or updates key=value)
# ------------------------------------------------------------
set_prop() {
  local key="$1" val="$2"
  [ -f "$CFG" ] || { echo "# Generated by entrypoint" > "$CFG"; }
  if ! grep -q -E "^${key}=" "$CFG"; then
    printf "%s=%s\n" "$key" "$val" >> "$CFG"
  else
    # escape &, /, and backslashes in replacement
    local esc
    esc=$(printf '%s\n' "$val" | sed -e 's/[&/\\]/\\&/g')
    sed -i -E "s|^(${key}=).*|\1${esc}|" "$CFG"
  fi
}

# ------------------------------------------------------------
# Write ALL corresponding server.properties keys
# ------------------------------------------------------------
set_prop "server-name"			             "$HOSTNAME"
set_prop "motd"                          "$MOTD"
set_prop "level-name"                    "$LEVEL_NAME"
set_prop "server-port"                   "$SERVER_PORT"
set_prop "server-ip"                     "$SERVER_IP"
set_prop "gamemode"                      "$GAMEMODE"
set_prop "generator-settings"            "$GENERATOR_SETTINGS"
set_prop "force-gamemode"                "$FORCE_GAMEMODE"
set_prop "allow-nether"                  "$ALLOW_NETHER"
set_prop "enforce-whitelist"             "$ENFORCE_WHITELIST"
set_prop "enable-query"                  "$ENABLE_QUERY"
set_prop "player-idle-timeout"           "$PLAYER_IDLE_TIMEOUT"
set_prop "difficulty"                    "$DIFFICULTY"
set_prop "spawn-monsters"                "$SPAWN_MONSTERS"
set_prop "op-permission-level"           "$OP_PERMISSION_LEVEL"
set_prop "pvp"                           "$PVP"
set_prop "snooper-enabled"               "$SNOOPER_ENABLED"
set_prop "level-type"                    "$LEVEL_TYPE"
set_prop "hardcore"                      "$HARDCORE"
set_prop "enable-command-block"          "$ENABLE_COMMAND_BLOCK"
set_prop "max-players"                   "$MAX_PLAYERS"
set_prop "network-compression-threshold" "$NETWORK_COMPRESSION_THRESHOLD"
set_prop "max-world-size"                "$MAX_WORLD_SIZE"
set_prop "spawn-npcs"                    "$SPAWN_NPCS"
set_prop "allow-flight"                  "$ALLOW_FLIGHT"
set_prop "view-distance"                 "$VIEW_DISTANCE"
set_prop "spawn-animals"                 "$SPAWN_ANIMALS"
set_prop "white-list"                    "$WHITE_LIST"
set_prop "generate-structures"           "$GENERATE_STRUCTURES"
set_prop "online-mode"                   "$ONLINE_MODE"
set_prop "max-build-height"              "$MAX_BUILD_HEIGHT"
set_prop "level-seed"                    "$LEVEL_SEED"
set_prop "prevent-proxy-connections"     "$PREVENT_PROXY_CONNECTIONS"
set_prop "use-native-transport"          "$USE_NATIVE_TRANSPORT"
set_prop "enable-rcon"                   "$ENABLE_RCON"
set_prop "rcon.password"                 "$RCON_PASSWORD"
set_prop "rcon.port"                     "$RCON_PORT"
set_prop "spawn-protection"              "$SPAWN_PROTECTION"
set_prop "max-tick-time"                 "$MAX_TICK_TIME"

if [ "$RESOURCE_PACK" != "" ]; then
  RESOURCE_SHA1=$(wget -qO- "$RESOURCE_PACK" --no-check-certificate | sha1sum | awk '{print $1}')
  set_prop "resource-pack" "$RESOURCE_PACK"
  set_prop "require-resource-pack" "true"
  set_prop "resource-pack-sha1" "$RESOURCE_SHA1"
else
  set_prop "resource-pack" ""
  set_prop "require-resource-pack" "false"
  set_prop "resource-pack-sha1" ""
fi

echo "----- server.properties -----"
cat "$CFG" || true
echo "-----------------------------"

yq -y -i '.motd."secondary-motd" = env.MOTD' "${MC_DIR}/plugins/Geyser-Spigot/config.yml"

if [ ! -f "$JAR" ]; then
  echo "Missing ${JAR}. Did the base image build succeed?" >&2
  exit 2
fi

echo "FRESH WORLD ${FRESH_WORLD}"
if [ "$FRESH_WORLD" = True ]; then
  if [ -d worlds/plotworld ]; then
    echo "DELETING OLD PLOTWORLD! /mc/plotworld"
    rm -rf /mc/plotworld/*
  else
    echo "DELETING OLD WORLD! /mc/world"
    rm -rf /mc/world/*
  fi
fi

# Handle custom download
if [ -n "$MAP_URL" ]; then
    mkdir -p /mc/world

    # check if the world directory is empty
    if [ -z "$(ls -A /mc/world 2>/dev/null)" ]; then
      echo "Downloading world from $MAP_URL..."
      wget -O download.zip "$MAP_URL" --no-check-certificate  && \
      unzip -q download.zip

      # Find the folder containing level.dat (the actual world root)
      WORLD_FOLDER=$(unzip -l download.zip \
        | awk '$4 ~ /level\.dat$/ {print $4}' \
        | sed 's|/level\.dat$||' \
        | head -n 1)
      echo "WORLD_FOLDER [$WORLD_FOLDER]"

      if [ -n "$WORLD_FOLDER" ] && [ -d "$WORLD_FOLDER" ]; then
        cp -R "$WORLD_FOLDER"/* /mc/world/
        echo "World [$WORLD_FOLDER] moved to ./world"
      else
        echo "Error: Could not find a folder containing level.dat"
        exit 1
      fi

      rm -rf download.zip
    fi
fi

if [ -d worlds/plotworld ]; then
    mkdir -p plotworld
    if [ -z "$(ls -A plotworld 2>/dev/null)" ]; then
        echo "Seeding saved world from default..."
        cp -R worlds/plotworld/* plotworld/
    fi
fi

echo "Starting Spigot for Minecraft ${MC_VERSION:-unknown} (Xms=${XMS}, Xmx=${XMX})..."
set +e
java ${JVM_OPTS} -Xms"${XMS}" -Xmx"${XMX}" -jar "${JAR}" nogui
echo "Minecraft crashed. Dropping to shell..."
exec bash